 # ASP.NET Core


# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'
  name: 'Default'
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any'
  buildConfiguration: 'Release'
  
steps:
#- script: dotnet build --configuration $(buildConfiguration)
#  displayName: 'dotnet build $(buildConfiguration)'

#- script: |
#    dotnet build --configuration $(buildConfiguration)
#  displayName: 'Build'

#- script: |
#    dotnet test --configuration $(buildConfiguration)
#  displayName: 'Test'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
  displayName: 'Publish Artifact'